#!/usr/bin/env python3
"""
Auto-generated by extract_examples.py -- do not edit manually.
Regenerate: python docs/tools/extract_examples.py

Renders VoxelCAD doc examples to PNG via PyVista offscreen.

Usage:
    python docs/tools/render_examples.py [--dry-run] [--filter PATTERN]
"""

import argparse
import os
import sys
import time
from pathlib import Path

os.environ.setdefault('VTK_SILENCE_GET_VOID_POINTER_WARNINGS', '1')

import pyvista as pv
pv.OFF_SCREEN = True

from voxelcad import Cube, Cylinder, GyroidCube, Sphere
from voxelcad.gyroid_cube import HyperWigglyGyroidCube, WigglyGyroidCube
import voxelcad.environment as ENV

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
IMAGES_DIR = REPO_ROOT / 'docs' / 'user' / '_images'


def render_model(model, output_path, window_size=(800, 600)):
    """Render a VoxelModel to PNG."""
    mesh = model.render_volume_mesh()
    pl = pv.Plotter(off_screen=True, window_size=window_size)
    pl.add_mesh(mesh, color='steelblue', show_edges=False)
    pl.camera_position = 'iso'
    pl.set_background('white')
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pl.screenshot(str(output_path))
    pl.close()


def render_boolean_operations__basic_usage__0():
    # Source: docs/user/boolean-operations.md
    # Section: Basic Usage (line 17)
    # Models: hollow, rounded_cube, combined
    from voxelcad import Sphere, Cube

    s = Sphere(r=4, voxel_size=0.2)
    c = Cube(size=6, voxel_size=0.2, center=True)

    hollow = s - Sphere(r=3.5, voxel_size=0.2)   # hollow sphere
    rounded_cube = s & c                           # sphere-clipped cube
    combined = s | c                               # merged shape

    render_model(hollow, IMAGES_DIR / 'boolean-operations' / 'basic-usage_0_hollow.png')
    render_model(rounded_cube, IMAGES_DIR / 'boolean-operations' / 'basic-usage_0_rounded_cube.png')
    render_model(combined, IMAGES_DIR / 'boolean-operations' / 'basic-usage_0_combined.png')


def render_boolean_operations__chaining__0():
    # Source: docs/user/boolean-operations.md
    # Section: Chaining (line 36)
    # Models: result
    from voxelcad import Sphere, Cube, Cylinder

    body = Cube(size=6, voxel_size=0.2, center=True)
    hole = Cylinder(h=8, r=1.5, center=True, voxel_size=0.2)

    # Cube with a cylindrical hole, intersected with a sphere
    result = (body - hole) & Sphere(r=4, voxel_size=0.2)

    render_model(result, IMAGES_DIR / 'boolean-operations' / 'chaining_0_result.png')


def render_boolean_operations__grid_matching__0():
    # Source: docs/user/boolean-operations.md
    # Section: Grid Matching (line 54)
    # Models: result
    # Fast: same voxel_size, byte-level bitwise ops
    a = Sphere(r=5, voxel_size=0.1)
    b = Cube(size=8, voxel_size=0.1, center=True)
    result = a & b  # direct bitwise_and on packed arrays

    # Slower: different voxel_size, requires resampling
    a = Sphere(r=5, voxel_size=0.1)
    b = Cube(size=8, voxel_size=0.2, center=True)
    result = a & b  # renders both to common grid first

    render_model(result, IMAGES_DIR / 'boolean-operations' / 'grid-matching_0_result.png')


def render_boolean_operations__difference_vs_xor__0():
    # Source: docs/user/boolean-operations.md
    # Section: Difference vs XOR (line 76)
    # Models: diff, xor
    s = Sphere(r=4, voxel_size=0.2)
    c = Cube(size=6, voxel_size=0.2, center=True)

    diff = s - c   # sphere with cube-shaped bite taken out
    xor = s ^ c    # shell-like shape where they don't overlap

    render_model(diff, IMAGES_DIR / 'boolean-operations' / 'difference-vs-xor_0_diff.png')
    render_model(xor, IMAGES_DIR / 'boolean-operations' / 'difference-vs-xor_0_xor.png')


def render_boolean_operations__inversion__0():
    # Source: docs/user/boolean-operations.md
    # Section: Inversion (line 92)
    # Models: mold
    s = Sphere(r=3, voxel_size=0.2)
    mold = Cube(size=8, voxel_size=0.2, center=True) & ~s  # cube with sphere-shaped cavity

    render_model(mold, IMAGES_DIR / 'boolean-operations' / 'inversion_0_mold.png')


def render_geometry_catalog__sphere__0():
    # Source: docs/user/geometry-catalog.md
    # Section: Sphere (line 18)
    # Models: sphere
    from voxelcad import Sphere

    sphere = Sphere(r=5, voxel_size=0.2)

    render_model(sphere, IMAGES_DIR / 'geometry-catalog' / 'sphere_0_sphere.png')


def render_geometry_catalog__cube__0():
    # Source: docs/user/geometry-catalog.md
    # Section: Cube (line 38)
    # Models: cube
    from voxelcad import Cube

    cube = Cube(size=8, voxel_size=0.2, center=True)

    render_model(cube, IMAGES_DIR / 'geometry-catalog' / 'cube_0_cube.png')


def render_geometry_catalog__cylinder__0():
    # Source: docs/user/geometry-catalog.md
    # Section: Cylinder (line 60)
    # Models: cylinder, cone
    from voxelcad import Cylinder

    cylinder = Cylinder(h=8, r=3, center=True, voxel_size=0.2)
    cone = Cylinder(h=8, r1=4, r2=0, voxel_size=0.2)

    render_model(cylinder, IMAGES_DIR / 'geometry-catalog' / 'cylinder_0_cylinder.png')
    render_model(cone, IMAGES_DIR / 'geometry-catalog' / 'cylinder_0_cone.png')


def render_geometry_catalog__gyroidcube__0():
    # Source: docs/user/geometry-catalog.md
    # Section: GyroidCube (line 95)
    # Models: gyroid, dense
    from voxelcad.gyroid_cube import GyroidCube

    gyroid = GyroidCube(10, voxel_size=0.05)
    dense = GyroidCube(10, lattice_param=2.0, voxel_size=0.05)

    render_model(gyroid, IMAGES_DIR / 'geometry-catalog' / 'gyroidcube_0_gyroid.png')
    render_model(dense, IMAGES_DIR / 'geometry-catalog' / 'gyroidcube_0_dense.png')


def render_geometry_catalog__wigglygyroidcube__0():
    # Source: docs/user/geometry-catalog.md
    # Section: WigglyGyroidCube (line 120)
    # Models: wiggly
    from voxelcad.gyroid_cube import WigglyGyroidCube

    wiggly = WigglyGyroidCube(10, thresh1=-0.5, thresh2=0.5, voxel_size=0.05)

    render_model(wiggly, IMAGES_DIR / 'geometry-catalog' / 'wigglygyroidcube_0_wiggly.png')


def render_geometry_catalog__hyperwigglygyroidcube__0():
    # Source: docs/user/geometry-catalog.md
    # Section: HyperWigglyGyroidCube (line 136)
    # Models: hyperwiggly
    from voxelcad.gyroid_cube import HyperWigglyGyroidCube

    hyperwiggly = HyperWigglyGyroidCube(10, thresh1=-0.5, thresh2=0.5, voxel_size=0.05)

    render_model(hyperwiggly, IMAGES_DIR / 'geometry-catalog' / 'hyperwigglygyroidcube_0_hyperwiggly.png')


def render_getting_started__your_first_model__0():
    # Source: docs/user/getting-started.md
    # Section: Your First Model (line 17)
    # Models: s
    from voxelcad import Sphere

    s = Sphere(r=5, voxel_size=0.1)
    s

    render_model(s, IMAGES_DIR / 'getting-started' / 'your-first-model_0_s.png')


def render_getting_started__boolean_operations__0():
    # Source: docs/user/getting-started.md
    # Section: Boolean Operations (line 32)
    # Models: union, intersection, difference, xor
    from voxelcad import Sphere, Cube

    s = Sphere(r=4, voxel_size=0.2)
    c = Cube(size=6, voxel_size=0.2, center=True)

    union        = s | c   # everything in either shape
    intersection = s & c   # only where both shapes overlap
    difference   = c - s   # cube with sphere carved out
    xor          = s ^ c   # where exactly one shape exists

    render_model(union, IMAGES_DIR / 'getting-started' / 'boolean-operations_0_union.png')
    render_model(intersection, IMAGES_DIR / 'getting-started' / 'boolean-operations_0_intersection.png')
    render_model(difference, IMAGES_DIR / 'getting-started' / 'boolean-operations_0_difference.png')
    render_model(xor, IMAGES_DIR / 'getting-started' / 'boolean-operations_0_xor.png')


def render_getting_started__transforms__0():
    # Source: docs/user/getting-started.md
    # Section: Transforms (line 54)
    # Models: moved, rotated, scaled
    s = Sphere(r=3, voxel_size=0.2)

    moved   = s.translate([0, 0, 5])     # shift along Z
    rotated = s.rotate_z(45)             # degrees
    scaled  = s.scale([2, 1, 0.5])       # per-axis scale factors

    render_model(moved, IMAGES_DIR / 'getting-started' / 'transforms_0_moved.png')
    render_model(rotated, IMAGES_DIR / 'getting-started' / 'transforms_0_rotated.png')
    render_model(scaled, IMAGES_DIR / 'getting-started' / 'transforms_0_scaled.png')


def render_getting_started__export_to_stl__0():
    # Source: docs/user/getting-started.md
    # Section: Export to STL (line 70)
    # Models: model
    model = Sphere(r=5, voxel_size=0.1) & Cube(size=8, voxel_size=0.1, center=True)

    render_model(model, IMAGES_DIR / 'getting-started' / 'export-to-stl_0_model.png')


def render_performance_guide__resolution_selection__0():
    # Source: docs/user/performance-guide.md
    # Section: Resolution Selection (line 18)
    # Models: coarse, medium, fine
    from voxelcad import Sphere

    coarse = Sphere(r=5, voxel_size=1.0)
    medium = Sphere(r=5, voxel_size=0.5)
    fine = Sphere(r=5, voxel_size=0.1)

    render_model(coarse, IMAGES_DIR / 'performance-guide' / 'resolution-selection_0_coarse.png')
    render_model(medium, IMAGES_DIR / 'performance-guide' / 'resolution-selection_0_medium.png')
    render_model(fine, IMAGES_DIR / 'performance-guide' / 'resolution-selection_0_fine.png')


def render_transforms__basic_usage__0():
    # Source: docs/user/transforms.md
    # Section: Basic Usage (line 17)
    # Models: moved, rotated, scaled, uniform
    from voxelcad import Sphere, Cylinder

    s = Sphere(r=3, voxel_size=0.2)
    moved = s.translate([0, 0, 10])     # shift 10 units along Z
    rotated = s.rotate_z(45)            # 45 degrees around Z
    scaled = s.scale([2, 1, 0.5])       # stretch X, squash Z
    uniform = s.scale(2.0)              # double all axes

    render_model(moved, IMAGES_DIR / 'transforms' / 'basic-usage_0_moved.png')
    render_model(rotated, IMAGES_DIR / 'transforms' / 'basic-usage_0_rotated.png')
    render_model(scaled, IMAGES_DIR / 'transforms' / 'basic-usage_0_scaled.png')
    render_model(uniform, IMAGES_DIR / 'transforms' / 'basic-usage_0_uniform.png')


def render_transforms__chaining__0():
    # Source: docs/user/transforms.md
    # Section: Chaining (line 37)
    # Models: placed
    arm = Cylinder(h=10, r=1, voxel_size=0.2)

    # Rotate, then move into position
    placed = arm.rotate_x(90).translate([5, 0, 0])

    render_model(placed, IMAGES_DIR / 'transforms' / 'chaining_0_placed.png')


def render_transforms__lazy_evaluation__0():
    # Source: docs/user/transforms.md
    # Section: Lazy Evaluation (line 58)
    # Models: result
    model = Sphere(r=2, voxel_size=0.1)
    result = model.translate([1,0,0]).rotate_z(30).scale(1.5).translate([0,5,0])
    # No computation until:
    result

    render_model(result, IMAGES_DIR / 'transforms' / 'lazy-evaluation_0_result.png')


def render_transforms__transforms_booleans__0():
    # Source: docs/user/transforms.md
    # Section: Transforms + Booleans (line 71)
    # Models: scoop_up, ice_cream, tilted
    from voxelcad import Sphere, Cylinder

    # Ice cream cone
    scoop = Sphere(r=3, voxel_size=0.2)
    cone = Cylinder(h=8, r1=3, r2=0, voxel_size=0.2)

    scoop_up = scoop.translate([0, 0, 8])    # lift scoop above cone
    ice_cream = scoop_up | cone               # combine
    tilted = ice_cream.rotate_x(15)           # tilt the whole thing

    render_model(scoop_up, IMAGES_DIR / 'transforms' / 'transforms-booleans_0_scoop_up.png')
    render_model(ice_cream, IMAGES_DIR / 'transforms' / 'transforms-booleans_0_ice_cream.png')
    render_model(tilted, IMAGES_DIR / 'transforms' / 'transforms-booleans_0_tilted.png')


def render_transforms__arbitrary_rotation__0():
    # Source: docs/user/transforms.md
    # Section: Arbitrary Rotation (line 91)
    # Models: rotated
    model = Sphere(r=3, voxel_size=0.2)
    rotated = model.rotate([1, 1, 0], 45)  # 45 degrees around the (1,1,0) axis

    render_model(rotated, IMAGES_DIR / 'transforms' / 'arbitrary-rotation_0_rotated.png')


def render_transforms__scale_caveats__0():
    # Source: docs/user/transforms.md
    # Section: Scale Caveats (line 104)
    # Models: disk
    # Thin disk: scale a sphere flat along Z
    disk = Sphere(r=5, voxel_size=0.05).scale([1, 1, 0.1])

    render_model(disk, IMAGES_DIR / 'transforms' / 'scale-caveats_0_disk.png')


def render_troubleshooting__boolean_result_looks_wrong__0():
    # Source: docs/user/troubleshooting.md
    # Section: Boolean result looks wrong (line 70)
    # Models: result
    a = Sphere(r=5, voxel_size=0.1)
    b = Cube(size=8, voxel_size=0.2)   # different!
    result = a & b                      # resampling may lose detail

    render_model(result, IMAGES_DIR / 'troubleshooting' / 'boolean-result-looks-wrong_0_result.png')


EXAMPLES = [
    ('boolean-operations/basic-usage_0', render_boolean_operations__basic_usage__0),
    ('boolean-operations/chaining_0', render_boolean_operations__chaining__0),
    ('boolean-operations/grid-matching_0', render_boolean_operations__grid_matching__0),
    ('boolean-operations/difference-vs-xor_0', render_boolean_operations__difference_vs_xor__0),
    ('boolean-operations/inversion_0', render_boolean_operations__inversion__0),
    ('geometry-catalog/sphere_0', render_geometry_catalog__sphere__0),
    ('geometry-catalog/cube_0', render_geometry_catalog__cube__0),
    ('geometry-catalog/cylinder_0', render_geometry_catalog__cylinder__0),
    ('geometry-catalog/gyroidcube_0', render_geometry_catalog__gyroidcube__0),
    ('geometry-catalog/wigglygyroidcube_0', render_geometry_catalog__wigglygyroidcube__0),
    ('geometry-catalog/hyperwigglygyroidcube_0', render_geometry_catalog__hyperwigglygyroidcube__0),
    ('getting-started/your-first-model_0', render_getting_started__your_first_model__0),
    ('getting-started/boolean-operations_0', render_getting_started__boolean_operations__0),
    ('getting-started/transforms_0', render_getting_started__transforms__0),
    ('getting-started/export-to-stl_0', render_getting_started__export_to_stl__0),
    ('performance-guide/resolution-selection_0', render_performance_guide__resolution_selection__0),
    ('transforms/basic-usage_0', render_transforms__basic_usage__0),
    ('transforms/chaining_0', render_transforms__chaining__0),
    ('transforms/lazy-evaluation_0', render_transforms__lazy_evaluation__0),
    ('transforms/transforms-booleans_0', render_transforms__transforms_booleans__0),
    ('transforms/arbitrary-rotation_0', render_transforms__arbitrary_rotation__0),
    ('transforms/scale-caveats_0', render_transforms__scale_caveats__0),
    ('troubleshooting/boolean-result-looks-wrong_0', render_troubleshooting__boolean_result_looks_wrong__0),
]


def main():
    parser = argparse.ArgumentParser(description='Render VoxelCAD doc examples')
    parser.add_argument('--dry-run', action='store_true',
                        help='List examples without rendering')
    parser.add_argument('--filter', type=str, default='',
                        help='Only render examples matching pattern')
    args = parser.parse_args()

    selected = [(label, fn) for label, fn in EXAMPLES if args.filter in label]

    if args.dry_run:
        for label, _ in selected:
            print(f'  {label}')
        print(f'\n{len(selected)} examples would be rendered.')
        print(f'Output: {IMAGES_DIR}/')
        return

    print(f'Rendering {len(selected)} examples to {IMAGES_DIR}/')
    failed = []
    for i, (label, fn) in enumerate(selected, 1):
        print(f'  [{i}/{len(selected)}] {label} ... ', end='', flush=True)
        t0 = time.time()
        try:
            fn()
            print(f'ok ({time.time() - t0:.1f}s)')
        except Exception as e:
            print(f'FAILED: {e}')
            failed.append((label, str(e)))

    print()
    if failed:
        print(f'{len(failed)} failures:')
        for label, err in failed:
            print(f'  {label}: {err}')
        sys.exit(1)
    else:
        print(f'All {len(selected)} examples rendered.')


if __name__ == '__main__':
    main()
